### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by Connor14** [jglrxavpok/Moar-Boats#38]
I'm using the latest version (3.0.0.1) on a Forge 14.23.4.2759 multiplayer server. Attached is a list of the mods on the server. This is a custom Curse modpack. We also have Galacticraft if it's not listed. 
[modlist.txt](https://github.com/jglrxavpok/Moar-Boats/files/2342682/modlist.txt)

When I first tried using the regular "modular boat", this appeared every time the server tried to save:
`[13:49:43] [Server thread/ERROR] [FML]: An Entity type org.jglrxavpok.moarboats.common.entities.ModularBoatEntity has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1769) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1651) ~[vg.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:361) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1740) ~[vg.class:?]
        ... 10 more`

It did not crash the server, but I wasn't able to reconnect. Other people on the server were just fine.

After I restarted the server and tried placing another boat, the server completely crashed with this message:
`[13:59:09] [Server thread/ERROR] [net.minecraft.entity.EntityTracker]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:256) [ol.class:?]
        at net.minecraftforge.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:369) [EntityRegistry.class:?]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:80) [ol.class:?]
        at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37) [op.class:?]
        at net.minecraft.world.World.func_72923_a(World.java:1218) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1112) [oo.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1209) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at org.jglrxavpok.moarboats.common.items.BaseBoatItem.func_77659_a(ModularBoatItem.kt:110) [BaseBoatItem.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) [aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1017) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:286) ~[AbstractChannel.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:341) ~[EmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:72) ~[FMLEmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:134) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:501) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:380) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73125_b(EntityTrackerEntry.java:490) ~[os.class:?]
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) ~[ol.class:?]
        ... 22 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
        at org.jglrxavpok.moarboats.common.entities.BasicBoatEntity.writeSpawnData(BasicBoatEntity.kt:879) ~[BasicBoatEntity.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:213) ~[FMLMessage$EntitySpawnMessage.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:42) ~[FMLRuntimeCodec.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:32) ~[FMLRuntimeCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1017) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:286) ~[AbstractChannel.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:341) ~[EmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:72) ~[FMLEmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:134) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:501) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:380) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73125_b(EntityTrackerEntry.java:490) ~[os.class:?]
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) ~[ol.class:?]
        ... 22 more
[13:59:09] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1017) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:286) ~[AbstractChannel.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:341) ~[EmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:72) ~[FMLEmbeddedChannel.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:134) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:501) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:380) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73125_b(EntityTrackerEntry.java:490) ~[os.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:143) ~[os.class:?]
        at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:292) ~[ol.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:779) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
        at org.jglrxavpok.moarboats.common.entities.BasicBoatEntity.writeSpawnData(BasicBoatEntity.kt:879) ~[BasicBoatEntity.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:213) ~[FMLMessage$EntitySpawnMessage.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:42) ~[FMLRuntimeCodec.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:32) ~[FMLRuntimeCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 21 more
[13:59:09] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/connor/Legion2018/./crash-reports/crash-2018-09-01_13.59.09-server.txt
[13:59:09] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[13:59:09] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[13:59:10] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: ChromeKnight_28 lost connection: Server closed
[13:59:10] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: ChromeKnight_28 left the game
[13:59:10] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[13:59:10] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Legion2018World'/overworld
[13:59:10] [Server thread/ERROR] [FML]: An Entity type org.jglrxavpok.moarboats.common.entities.ModularBoatEntity has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1769) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1651) ~[vg.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:361) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
        at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1740) ~[vg.class:?]
        ... 10 more
[13:59:10] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Legion2018World'/ExtraUtils2_Quarry_Dim
[13:59:10] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Legion2018World'/Storage Cell
[13:59:11] [Server thread/INFO] [FML]: Unloading dimension 0
[13:59:11] [Server thread/INFO] [FML]: Unloading dimension -9999
[13:59:11] [Server thread/INFO] [FML]: Unloading dimension 2
[13:59:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 2 data blobs
[13:59:11] [Server thread/INFO] [fluxnetworks]: Cleared Network Caches
[13:59:11] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[13:59:11] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[13:59:11] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[13:59:11] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[13:59:11] [Server thread/INFO] [projecte]: Completed server-stop actions.
[13:59:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools Dimensions: server is stopping. Shutting down gracefully
[13:59:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
[13:59:11] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[13:59:11] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[13:59:11] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
`

**Comment by jglrxavpok** [comment]
Could you please send me the full crash log? Also try with Forge 14.23.4.2758 as 2759 has some issues. I will investigate on my end

**Comment by Connor14** [comment]
@jglrxavpok Attached is the full server log. Let me know if you need something different.
[2018-09-01-3.log](https://github.com/jglrxavpok/Moar-Boats/files/2342941/2018-09-01-3.log)

**Comment by Connor14** [comment]
And here is the crash log
[crash-2018-09-01_13.59.09-server.txt](https://github.com/jglrxavpok/Moar-Boats/files/2342943/crash-2018-09-01_13.59.09-server.txt)

**Comment by Connor14** [comment]
@jglrxavpok I just tried with forge 14.23.4.2758 and the same issue occurred. Attached is the server log. There was no crash this time, so all I have is the latest log

[latest.log](https://github.com/jglrxavpok/Moar-Boats/files/2386849/latest.log)

**Comment by jglrxavpok** [comment]
Should be fixed in 3.0.0.2 https://minecraft.curseforge.com/projects/moar-boats/files/2620807 (wait for it to be approved by CurseForge)
