### ISSUE TITLE
Boat disappears when placed in water

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#40]
moarboats-1.12.2-3.0.0.1.jar

When placing boat in water it immediately disappears and I get this in the log - 

[22:45:02] [Server thread/ERROR] [FML]: An Entity type org.jglrxavpok.moarboats.common.entities.ModularBoatEntity has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1769) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1651) ~[vg.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:361) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1740) ~[vg.class:?]
	... 10 more
[22:45:02] [Server thread/ERROR] [FML]: An Entity type org.jglrxavpok.moarboats.common.entities.ModularBoatEntity has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1769) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1651) ~[vg.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:361) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_192396_c()Ljava/lang/String;
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.func_70014_b(ModularBoatEntity.kt:190) ~[ModularBoatEntity.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1740) ~[vg.class:?]

**Comment by jglrxavpok** [comment]
This is a dup of #38 but I just found the fix, I will release a version soon to fix this issue

**Comment by jglrxavpok** [comment]
https://minecraft.curseforge.com/projects/moar-boats/files/2620807 this should fix it (wait for it to be approved by CurseForge)
