### ISSUE TITLE
Map not rendering when editing waypoints

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#45]
Moar-Boats Ver 1.12.2-3.0.0.2
Not sure if same issue as #44 
When trying to edit waypoints the map does not render at all just a transparent area. The markers do appear however. This is in the server console when you click to edit.

[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraft.block.material.MapColor.func_151643_b(I)I
[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler.takeScreenshotOfMapArea(C10MapImageRequest.kt:95)
[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler.access$takeScreenshotOfMapArea(C10MapImageRequest.kt:45)
[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler$onMessage$$inlined$repeat$lambda$1.invoke(C10MapImageRequest.kt:61)
[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler$onMessage$$inlined$repeat$lambda$1.invoke(C10MapImageRequest.kt:45)
[10:53:21] [Thread-71/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: net.minecraft.block.material.MapColor.func_151643_b(I)I
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler.takeScreenshotOfMapArea(C10MapImageRequest.kt:95)
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler.access$takeScreenshotOfMapArea(C10MapImageRequest.kt:45)
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler$onMessage$$inlined$repeat$lambda$1.invoke(C10MapImageRequest.kt:61)
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jglrxavpok.moarboats.common.network.C10MapImageRequest$Handler$onMessage$$inlined$repeat$lambda$1.invoke(C10MapImageRequest.kt:45)
[10:53:21] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by jglrxavpok** [comment]
This is fixed in the 4.0 (mapping-table) branch
