### ISSUE TITLE
[1.16.4, beta3] Dedicated server crash

### ISSUE THREAD

**Issue by kanauru** [jglrxavpok/Moar-Boats#97]
Works fine in single player but I get an error when trying to use it on a dedicated server

`[23:48:08] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Moar Boats (moarboats) has failed to load correctly
§7java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/PlayerModel
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:262) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:187) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.3-34.1.42.jar:34.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.3-34.1.42.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.3-34.1.42.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.3-34.1.42.jar:?] {}
`

**Comment by kanauru** [comment]
Nevermind. I fixed the issue by downgrading to Kotlin  1.6.1

**Comment by kanauru** [comment]
Whoops, the problem still persists 

`[00:29:40] [modloading-worker-0/ERROR] [th.ko.LoggerKt/LOADING]: Failed to create mod instance. ModID: moarboats, class org.jglrxavpok.moarboats.MoarBoats
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/PlayerModel
        at org.jglrxavpok.moarboats.client.ClientEvents.<clinit>(ClientEvents.kt:73) ~[moarboats:1.16.3-8.0.0.0-beta3] {re:classloading,pl:runtimedistcleaner:A}
        at org.jglrxavpok.moarboats.MoarBoats.<clinit>(MoarBoats.kt:151) ~[moarboats:1.16.3-8.0.0.0-beta3] {re:classloading}
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186) ~[?:?] {re:classloading,re:classloading}
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105) ~[?:?] {}
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1086) ~[?:?] {}
        at java.lang.reflect.Field.get(Field.java:418) ~[?:?] {}
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:116) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt) ~[?:?] {re:classloading}
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:241) ~[?:?] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:152) ~[?:1.6.1] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainer.access$constructMod(KotlinModContainer.kt:26) ~[?:1.6.1] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainer$1.invoke(KotlinModContainer.kt:64) ~[?:1.6.1] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainer$1.invoke(KotlinModContainer.kt:26) ~[?:1.6.1] {re:classloading}
        at thedarkcolour.kotlinforforge.KotlinModContainerKt$sam$java_lang_Runnable$0.run(KotlinModContainer.kt) ~[?:1.6.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.PlayerModel
        at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        ... 27 more
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
                at org.jglrxavpok.moarboats.client.ClientEvents.<clinit>(ClientEvents.kt:73) ~[moarboats:1.16.3-8.0.0.0-beta3] {re:classloading,pl:runtimedistcleaner:A}
                at org.jglrxavpok.moarboats.MoarBoats.<clinit>(MoarBoats.kt:151) ~[moarboats:1.16.3-8.0.0.0-beta3] {re:classloading}
                at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {re:classloading,re:classloading}
                at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042) ~[?:?] {re:classloading,re:classloading}
                at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43) ~[?:?] {re:classloading,re:classloading}
                at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186) ~[?:?] {re:classloading,re:classloading}
                at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105) ~[?:?] {}
                at java.lang.reflect.Field.getFieldAccessor(Field.java:1086) ~[?:?] {}
                at java.lang.reflect.Field.get(Field.java:418) ~[?:?] {}
                at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:116) ~[?:?] {re:classloading}
                at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62) ~[?:?] {re:classloading}
                at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?] {re:classloading}
                at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt) ~[?:?] {re:classloading}
                at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:241) ~[?:?] {re:classloading}
                at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:152) ~[?:1.6.1] {re:classloading}
                at thedarkcolour.kotlinforforge.KotlinModContainer.access$constructMod(KotlinModContainer.kt:26) ~[?:1.6.1] {re:classloading}
                at thedarkcolour.kotlinforforge.KotlinModContainer$1.invoke(KotlinModContainer.kt:64) ~[?:1.6.1] {re:classloading}
                at thedarkcolour.kotlinforforge.KotlinModContainer$1.invoke(KotlinModContainer.kt:26) ~[?:1.6.1] {re:classloading}
                at thedarkcolour.kotlinforforge.KotlinModContainerKt$sam$java_lang_Runnable$0.run(KotlinModContainer.kt) ~[?:1.6.1] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
`

**Comment by BraveCaperCat2** [comment]
the server doesn't contain the class for players. try removing on the server.
